In [ ]:
!pip install pandas nltk scikit-learn

Requirement already satisfied: pandas in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (2.2.3)
Requirement already satisfied: nltk in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (3.9.3)
Requirement already satisfied: scikit-learn in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (1.6.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: click in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from nltk) (8.1.8)
Requirement already satisfied: joblib in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from nltk) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from nltk) (2026.2.28)
Requirement already satisfied: tqdm in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from nltk) (4.67.3)
Requirement already satisfied: scipy>=1.6.0 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (1.15.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: colorama in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from click->nltk) (0.4.6)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
import pandas as pd
import numpy as np
import nltk
import re

from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import joblib

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [ ]:
data = pd.read_csv("food_reviews_dataset_realistic_6000.csv")
data.head()

,Dish,Review,Sentiment
0,Aloo Paratha,The Aloo Paratha was not fresh and delivery wa...,0
1,Mutton Biryani,The Mutton Biryani was burnt taste and ambienc...,0
2,Lassi,The Lassi was rich and flavorful and service w...,1
3,Masala Dosa,The Masala Dosa was well prepared and delivery...,1
4,Veg Pulao,The Veg Pulao was loved every bite and service...,1

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(
    max_features=8000,
    ngram_range=(1,2)
)

In [ ]:
ps = PorterStemmer()
stop_words = set(stopwords.words('english'))

def clean_text(text):
    text = text.lower()
    text = re.sub('[^a-z]', ' ', text)
    words = text.split()
    words = [ps.stem(word) for word in words if word not in stop_words]
    return " ".join(words)

data['Cleaned_Review'] = data['Review'].apply(clean_text)
data.head()

,Dish,Review,Sentiment,Cleaned_Review
0,Aloo Paratha,The Aloo Paratha was not fresh and delivery wa...,0,aloo paratha fresh deliveri delay
1,Mutton Biryani,The Mutton Biryani was burnt taste and ambienc...,0,mutton biryani burnt tast ambienc noisi
2,Lassi,The Lassi was rich and flavorful and service w...,1,lassi rich flavor servic quick
3,Masala Dosa,The Masala Dosa was well prepared and delivery...,1,masala dosa well prepar deliveri fast
4,Veg Pulao,The Veg Pulao was loved every bite and service...,1,veg pulao love everi bite servic quick

In [ ]:
TfidfVectorizer(max_features=5000, ngram_range=(1,2))
X = vectorizer.fit_transform(data['Cleaned_Review']).toarray()

y = data['Sentiment']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [ ]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [ ]:
y_pred = model.predict(X_test)
y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 1.0

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       595
           1       1.00      1.00      1.00       581

    accuracy                           1.00      1176
   macro avg       1.00      1.00      1.00      1176
weighted avg       1.00      1.00      1.00      1176


Confusion Matrix:
 [[595   0]
 [  0 581]]
Accuracy: 1.0

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       595
           1       1.00      1.00      1.00       581

    accuracy                           1.00      1176
   macro avg       1.00      1.00      1.00      1176
weighted avg       1.00      1.00      1.00      1176


Confusion Matrix:
 [[595   0]
 [  0 581]]

In [ ]:
joblib.dump(model, "advanced_sentiment_model.pkl")
joblib.dump(vectorizer, "advanced_tfidf_vectorizer.pkl")

['advanced_tfidf_vectorizer.pkl']

In [ ]:
def predict_review(review):
    review_clean = clean_text(review)
    review_vector = vectorizer.transform([review_clean]).toarray()
    prediction = model.predict(review_vector)
    
    if prediction[0] == 1:
        return "Positive 😊"
    else:
        return "Negative 😞"

print(predict_review("Mutton biryani was tasty"))
print(predict_review("Dosa was cold and horrible"))

Positive 😊
Negative 😞

In [ ]:
data[data["Review"].str.contains("tasty", case=False)].head()

Empty DataFrame
Columns: [Dish, Review, Sentiment, Cleaned_Review]
Index: []